<?php echo '
<div class="container">
    <div class="card w-75">
        <div class="card-body">
            <h5 class="card-title">Tere tulemast ametliku identiteediga kasutajate hulka,
                ' . $this->userData->person->firstName . ' ' . $this->userData->person->middleName ? $this->userData->person->middleName . ' ' : '' . $this->userData->person->lastName . '!
            </h5>
            <div class="card-text">
                Kuna olete esimest korda sisse logimas, siis lõime teie jaoks automaatselt kasutajakonto.
                Kuna sisenete Id-kaardiga autentides, siis tekib lisaks kasutajakontole ka teie isikukirje. Hiljem võite
                soovi korral siduda sellesama isikukirjega ka oma teisi kontosid.<br>
                Kui kasutajakonto on seotud igati ametlikult eksisteeriva isikuga, siis lisab see kasutajale piisavalt
                usaldusväärsust, et anda talle teatud eeliseid ligipääsuks sisule. See funktsonaalsus pole küll veel
                valmis (ligipääsuõiguste haldamine), kuid on kindlasti plaanis.<br>
                <button class="btn btn-warning btn-lg" onclick="window.location.href=\'\';">
                    Sain aru, jätkan
                </button>
            </div>
        </div>
    </div>
</div>
';